services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8083:8083"
    volumes:
      - ./src:/app/src
      - ./credentials.json:/app/credentials.json
    environment:
      - ENVIRONMENT=local
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    env_file:
      - .env.local